var x = 5;
try {
    x = x5 / 0;
}
catch (err) {
    console.log("Error (5/0)");
}
